### ISSUE TITLE
Test if web authenticator handle android open file chooser

### ISSUE THREAD

**Issue by roxk** [authgear/authgear-sdk-xamarin#21]

**Comment by roxk** [comment]
What urls can I test this behavior? Login and then open settings?

**Comment by fungc-io** [comment]
yes, login and open settings and try upload a profilepic

**Comment by roxk** [comment]
If I can upload picture does it mean it's fine? Or must the system show activity chooser? I forgot what will happen if the relevant method isn't implemented...No response when clicking upload  new picture?

**Comment by louischan-oursky** [comment]
> if the relevant method isn't implemented...No response when clicking upload new picture?

Yes. 

> Or must the system show activity chooser?

No. If the default file chooser can pop up, that's fine.

**Comment by louischan-oursky** [comment]
What about OpenUrl?

**Comment by louischan-oursky** [comment]
Oh, we use CustomTabs for both authentication and settings page

**Comment by roxk** [comment]
I was testing open url so open url is working as expected already. But wait, open url is simply using custom tabs on android. So what I was testing was custom tabs work. I will need authenticate -> settings now.

**Comment by fungc-io** [comment]
I confirm I can upload profile pic on android xamarin demo app

**Comment by roxk** [comment]
> we use CustomTabs for both authentication and settings page

Yes. Open url is implemented with manual custom tab, authentication is implemented with xamarin's web authenticator, it's using custom tab internally as well I believe.
