### ISSUE TITLE
Add ConfigureAwait(false) where appropriate

### ISSUE THREAD

**Issue by roxk** [authgear/authgear-sdk-xamarin#35]
Authgear is a library so it doesn't need to resume on the original synchronization context.

https://devblogs.microsoft.com/dotnet/configureawait-faq/

- [x] Add test to test call resume on caller thread

**Comment by roxk** [comment]
@fungc-io @louischan-oursky Are there any active customers of the sdk now? Is the potential client testing it already? This change while desirable can be breaking. Essentially, after awaiting, the thread can be on a background thread. I tested in sample app, while some code magically still work (e.g. property changed, which update UI, which is a surprise as this would probably throw in other framework), I don't wanna risk introducing bugs in client code.

**Comment by louischan-oursky** [comment]
I haven't read the article. Is this issue about the thread running the awaited code not main thread? We do call some framework methods in the SDK so I think we better ensure our SDK always run in main thread.

**Comment by fungc-io** [comment]
There is no active customer using the Xamarin SDK at the moment. No problem to fix this issue.

**Comment by roxk** [comment]
@louischan-oursky It's about how the sdk internally doesn't have to always go back to main thread, only to call IO work which would be working on background threads anyways. I tested in android and most calls do not need to be called in main thread, or the code path leading to framework call didn't involve thread switching (i.e. no await).

TODO:
- Decide if our sdk's public method guarantee resuming thread == calling thread
  - In android, only java guarantee it should be called in main thread, and the thread for the callback is determined by the handler parameter. Kotlin does _not_ dictate what the coroutine context should be. Authgear core internally doesn't dictate what the context of the suspend functions are as well so by default they execute on whatever thread the caller was calling
  - iOS TBC
  - flutter single thread by default
  - React Native single thread only
  - Xamarin, old SDK without `ConfigureAwait(false)` by default resume on the caller's thread. So if the sdk's methods are called in background thread, the call resume on background, if called on the main thread, resume on the main thread.

**Comment by louischan-oursky** [comment]
> Xamarin, old SDK without ConfigureAwait(false) by default resume on the caller's thread. So if the sdk's methods are called in background thread, the call resume on background, if called on the main thread, resume on the main thread.

This is a predictable behavior. Let's keep it

> Xamarin: No, execute on whatever thread the SDK was called on

Listener should be called on main thread. It is the most predictable behavior.

**Comment by roxk** [comment]
> This is a predictable behavior. Let's keep it
Note that this has to be on the doc. Lemme update README and doc reference.
