### ISSUE TITLE
Switch to build demo app with GitHub Actions or make it build-able in app center

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-sdk-xamarin#40]
Appcenter does not support .NET Core 6

**Comment by roxk** [comment]
I think only UnitTest is targeting .NET 6. Can simply target .NET 5 for now.

**Comment by louischan-oursky** [comment]
The resolution is downgrade UnitTest to .NET 5 and continue to build on AppCenter https://github.com/authgear/authgear-sdk-xamarin/commit/c250edb120e5f8fb9eb18fb7cf982c4cea34908c
